<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dell-PC" ignored="0" name="Test" tests="18" failures="3" timestamp="14 Aug 2021 17:26:49 GMT" time="62.49" errors="0">
  <testcase name="checkTestFive" time="9.991" classname="testcasesbigin.LoginAutomation">
    <failure type="java.lang.AssertionError" message="expected [Kiran] but found [Kiran
Online]">
      <![CDATA[java.lang.AssertionError: expected [Kiran] but found [Kiran
Online]
	at testcasesbigin.LoginAutomation.checkTestFive(LoginAutomation.java:71)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkTestFive -->
  <testcase name="checkTestFour" time="8.152" classname="testcasesbigin.LoginAutomation"/>
  <testcase name="checkTestOne" time="7.546" classname="testcasesbigin.LoginAutomation"/>
  <testcase name="checkTestThree" time="7.454" classname="testcasesbigin.LoginAutomation"/>
  <testcase name="checkTestTwo" time="7.303" classname="testcasesbigin.LoginAutomation"/>
  <testcase name="checkTestThree" time="0.004" classname="testcasesbigin.SignuppTestCase"/>
  <testcase name="checkTestTwo" time="0.003" classname="testcasesbigin.SignuppTestCase"/>
  <testcase name="checkTestfour" time="0.003" classname="testcasesbigin.SignuppTestCase"/>
  <testcase name="checkTestFive" time="0.003" classname="testcasesbigin.LoginTestCases"/>
  <testcase name="checkTestOne" time="0.003" classname="testcasesbigin.LoginTestCases">
    <failure type="java.lang.AssertionError" message="expected [5] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [2]
	at testcasesbigin.LoginTestCases.checkTestOne(LoginTestCases.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkTestOne -->
  <testcase name="checkTestThree" time="0.029" classname="testcasesbigin.LoginTestCases"/>
  <testcase name="checkTestTwo" time="0.006" classname="testcasesbigin.LoginTestCases"/>
  <testcase name="checkTestfour" time="0.004" classname="testcasesbigin.LoginTestCases">
    <failure type="java.lang.AssertionError" message="expected [5] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [3]
	at testcasesbigin.LoginTestCases.checkTestfour(LoginTestCases.java:28)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkTestfour -->
  <testcase name="checkTestFive" time="3.746" classname="testcasesbigin.AutoLoginTestCase"/>
  <testcase name="checkTestFour" time="4.104" classname="testcasesbigin.AutoLoginTestCase"/>
  <testcase name="checkTestOne" time="4.19" classname="testcasesbigin.AutoLoginTestCase"/>
  <testcase name="checkTestThree" time="4.466" classname="testcasesbigin.AutoLoginTestCase"/>
  <testcase name="checkTestTwo" time="5.257" classname="testcasesbigin.AutoLoginTestCase"/>
</testsuite> <!-- Test -->
